Changed yaml files

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,10 +1,6 @@
 name: CI
 
-on:
-  push:
-  pull_request:
-  schedule:
-    - cron: '0 0 * * 0'
+on: [push]
 
 jobs:
   verify:
@@ -15,20 +11,64 @@ jobs:
         java: [7, 8, 11]
 
     steps:
+      - uses: actions/setup-python@v2
+        with:
+          python-version: '3.10'
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install pandas
+          pip install numpy
+      - run: sudo apt update
+      - run: sudo apt install inotify-tools
+      - run: inotifywait -mr /home/runner/work/socket.io-client-java/socket.io-client-java/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
+      - run: touch starting_verify_uses-checkout_18
+      - run: rm starting_verify_uses-checkout_18
       - uses: actions/checkout@v2
+      - run: touch starting_verify_Setupjava_19
+      - run: rm starting_verify_Setupjava_19
       - name: Setup java
         uses: actions/setup-java@v1
         with:
           java-version: ${{ matrix.java }}
+      - run: touch starting_verify_CacheMavenpackages_23
+      - run: rm starting_verify_CacheMavenpackages_23
       - name: Cache Maven packages
         uses: actions/cache@v2
         with:
           path: ~/.m2
           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
           restore-keys: ${{ runner.os }}-m2
+      - run: touch starting_verify_SetupNodejs_29
+      - run: rm starting_verify_SetupNodejs_29
       - name: Setup Node.js
         uses: actions/setup-node@v1
         with:
           node-version: 14.x
+      - run: touch starting_verify_RuntheMavenverifyphase_33
+      - run: rm starting_verify_RuntheMavenverifyphase_33
       - name: Run the Maven verify phase
         run: mvn verify -Dgpg.skip=true
+      - run: touch starting_finished_finished_8979874
+        if: always()
+      - run: rm starting_finished_finished_8979874
+        if: always()
+      - name: Execute py script # run file
+        if: always()
+        run: |
+          echo pwd
+          ls -la
+          python .github/workflows/script.py
+      - name: Check push directory exit code
+        if: always()
+        run: |
+          echo 'push failed, trying pull and then push'
+          git config --global user.name 'UT-SE-Research'
+          git config --global user.email 'ocibsummerresearch2022@gmail.com'
+          git add .
+          git commit -m 'rebased and pushed ${{ github.head_ref }}'
+          while ! git push origin 1676957968-c0ae930; do
+            git pull --rebase https://github.com/UT-SE-Research/ci-analyzes.git 1676957968-c0ae930
+            git remote set-url origin https://UT-SE-Research:${{ secrets.API_TOKEN_GITHUB }}@github.com/UT-SE-Research/ci-analyzes.git
+            git push -f origin 1676957968-c0ae930
+          done
